import CryptoKit
import Foundation

/// Offline, store-agnostic licensing.
///
/// License keys are Ed25519-signed `payload.signature` tokens issued with the
/// private key (see `script/license_tool.swift`). The app embeds only the
/// public key and verifies keys entirely offline, so it works with any
/// storefront (Paddle / Lemon Squeezy / Gumroad webhook, or hand-issued keys).
///
/// A 14-day full-feature trial runs from first launch; after it ends an
/// unlicensed app keeps running but stops auto-locking until a key is entered.
@MainActor
final class LicenseStore: ObservableObject {
  enum Status: Equatable {
    case trial(daysLeft: Int)
    case expired
    case licensed(payload: String)
  }

  /// Public verification key (base64). Generated by `license_tool.swift
  /// generate-keys`; the matching private key is kept out of the repo.
  static let publicKeyBase64 = "S0lRconPC0pCql0jM/ZKYsbng597HrrvUc1hOReujwU="

  static let trialDays = 14

  /// Where "Buy" sends users. TODO: point at the live storefront before launch.
  static let purchaseURL = URL(string: "https://github.com/akash-viven/WalkAway")!

  @Published private(set) var status: Status

  private let defaults: UserDefaults

  init(defaults: UserDefaults = .standard) {
    self.defaults = defaults

    let firstLaunch: Date
    if let stored = defaults.object(forKey: Keys.firstLaunch) as? Date {
      firstLaunch = stored
    } else {
      firstLaunch = Date()
      defaults.set(firstLaunch, forKey: Keys.firstLaunch)
    }

    if let key = defaults.string(forKey: Keys.licenseKey),
       let payload = Self.verifiedPayload(for: key) {
      status = .licensed(payload: payload)
    } else {
      status = Self.trialStatus(firstLaunch: firstLaunch)
    }
  }

  /// True while the app is allowed to auto-lock.
  var isEntitled: Bool {
    switch status {
    case .licensed, .trial:
      return true
    case .expired:
      return false
    }
  }

  var isLicensed: Bool {
    if case .licensed = status { return true }
    return false
  }

  /// Validate and persist a pasted key. Returns true on success.
  @discardableResult
  func activate(_ rawKey: String) -> Bool {
    let key = rawKey.trimmingCharacters(in: .whitespacesAndNewlines)
    guard let payload = Self.verifiedPayload(for: key) else { return false }
    defaults.set(key, forKey: Keys.licenseKey)
    status = .licensed(payload: payload)
    return true
  }

  // MARK: - Verification

  private static func trialStatus(firstLaunch: Date) -> Status {
    let elapsedDays = Calendar.current.dateComponents([.day], from: firstLaunch, to: Date()).day ?? 0
    let left = trialDays - elapsedDays
    return left > 0 ? .trial(daysLeft: left) : .expired
  }

  /// Returns the signed payload string if the key verifies against the
  /// embedded public key, otherwise nil.
  static func verifiedPayload(for key: String) -> String? {
    let parts = key.split(separator: ".")
    guard parts.count == 2,
          let pubData = Data(base64Encoded: publicKeyBase64),
          let pub = try? Curve25519.Signing.PublicKey(rawRepresentation: pubData),
          let payload = base64urlDecode(String(parts[0])),
          let signature = base64urlDecode(String(parts[1])),
          pub.isValidSignature(signature, for: payload) else {
      return nil
    }
    return String(data: payload, encoding: .utf8)
  }

  private static func base64urlDecode(_ string: String) -> Data? {
    var s = string.replacingOccurrences(of: "-", with: "+").replacingOccurrences(of: "_", with: "/")
    while s.count % 4 != 0 { s += "=" }
    return Data(base64Encoded: s)
  }

  private enum Keys {
    static let firstLaunch = "licenseFirstLaunch"
    static let licenseKey = "licenseKey"
  }
}
